[package]
name = "sentinel-engine"
version = "0.2.0"
edition = "2024"
publish = false

[dependencies]
alloy.workspace = true
argh.workspace = true
async-trait.workspace = true
axum.workspace = true
safe-tx.workspace = true
safenet-core.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true
tower-http.workspace = true
tracing.workspace = true
