//! The validator effect system and its handler.

use crate::{
    bindings,
    frost::{
        self,
        keygen::{KeyShare, Secrets},
        sign::SigningNonces,
    },
    metrics::{self, EffectKind, Outcome},
    secrets::{SecretStore, store::RetainedSecrets},
};
use alloy::primitives::{Address, B256};
use safenet_core::{effects::EffectHandler, index::BlockStatus};
use std::{
    collections::BTreeMap,
    error::Error,
    fmt::{self, Display, Formatter},
    sync::Arc,
};

/// An impure operation the state transition asks the handler to perform.
#[derive(Debug, Clone)]
pub enum Effect {
    /// Set up key generation: sample the participant's secrets, persist them
    /// to the secret store.
    KeyGenSetup {
        group_id: B256,
        count: u16,
        threshold: u16,
    },
    /// Generate and persist this validator's nonces for the signing ceremony
    /// `signature_id`. Repeating it for the same ceremony returns the nonces
    /// generated the first time.
    GenerateNonces {
        group_id: B256,
        signature_id: B256,
        key_share: Arc<KeyShare>,
    },
    /// Use this validator's own nonces for the signing ceremony
    /// `signature_id`. Once the nonces are taken, they are burned and can no
    /// longer be used.
    UseNonces { message: B256, signature_id: B256 },
    /// Reconcile the persisted secrets with the groups retained by the state
    /// machine as of `block`, scheduling all secret material belonging to
    /// other groups for deletion.
    ReconcileGroupSecrets {
        block: u64,
        groups: BTreeMap<B256, RetainedSecrets>,
    },
}

impl Effect {
    /// Returns the stable label value used to identify this effect in metrics.
    fn metric_kind(&self) -> EffectKind {
        match self {
            Self::KeyGenSetup { .. } => EffectKind::KeyGenSetup,
            Self::GenerateNonces { .. } => EffectKind::GenerateNonces,
            Self::UseNonces { .. } => EffectKind::UseNonces,
            Self::ReconcileGroupSecrets { .. } => EffectKind::ReconcileGroupSecrets,
        }
    }
}

/// The result of performing an [`Effect`], resumed into the state machine.
#[derive(Debug, Clone, Default)]
pub enum Resume {
    /// An effect that does not require resuming.
    #[default]
    Noop,
    /// Resume with the key gen commitment produced by a [`Effect::KeyGenSetup`].
    Setup {
        group_id: B256,
        secrets: Box<Secrets>,
    },
    /// Resume with the nonce commitments generated by a
    /// [`Effect::GenerateNonces`].
    NonceCommitments {
        signature_id: B256,
        nonces: bindings::SignNonces,
    },
    /// Resume with the nonces burned by [`Effect::UseNonces`].
    Nonces {
        message: B256,
        nonces: Box<SigningNonces>,
    },
}

/// Performs the validator's [`Effect`]s, resuming with a [`Resume`].
pub struct Handler {
    /// The account of the running validator.
    account: Address,
    /// The secret store containing randomly generated secrets.
    secrets: SecretStore,
}

impl Handler {
    /// Creates an effect handler.
    pub fn new(account: Address, secrets: SecretStore) -> Self {
        Self { account, secrets }
    }

    async fn try_perform_effect(&self, effect: Effect) -> Result<Resume, InternalError> {
        match effect {
            Effect::KeyGenSetup {
                group_id,
                count,
                threshold,
            } => {
                let secrets = {
                    let mut rng = rand::thread_rng();
                    frost::keygen::setup(&mut rng, self.account, count, threshold)?
                };
                let stored = self
                    .secrets
                    .store_keygen_secrets(group_id, self.account, secrets)
                    .await?;
                Ok(Resume::Setup {
                    group_id,
                    secrets: Box::new(stored),
                })
            }
            Effect::GenerateNonces {
                group_id,
                signature_id,
                key_share,
            } => {
                let nonces = {
                    let mut rng = rand::thread_rng();
                    SigningNonces::generate(&key_share, &mut rng)
                };
                Ok(self
                    .secrets
                    .store_signing_nonces(group_id, signature_id, self.account, nonces)
                    .await?
                    .map(|nonces| Resume::NonceCommitments {
                        signature_id,
                        nonces: nonces.commitments(),
                    })
                    .unwrap_or(Resume::Noop))
            }
            Effect::UseNonces {
                message,
                signature_id,
            } => Ok(self
                .secrets
                .take_signing_nonces(signature_id)
                .await?
                .map(|nonces| Resume::Nonces {
                    message,
                    nonces: Box::new(nonces),
                })
                .unwrap_or(Resume::Noop)),
            Effect::ReconcileGroupSecrets { block, groups } => {
                if !self
                    .secrets
                    .schedule_group_secrets_deletion(block, &groups)
                    .await?
                {
                    // A reconciliation older than the last accepted one no
                    // longer describes the groups being tracked, so leave the
                    // schedules as they are.
                    tracing::debug!(block, "ignoring outdated group secret reconciliation");
                }
                Ok(Resume::Noop)
            }
        }
    }
}

impl EffectHandler<Effect, Resume> for Handler {
    async fn perform_effect(&self, effect: Effect) -> Resume {
        let kind = effect.metric_kind();
        let (resume, result) = match self.try_perform_effect(effect.clone()).await {
            Ok(resume) => (resume, Outcome::Success),
            Err(err) => {
                tracing::warn!(?effect, %err, "failed to perform effect");
                (Resume::Noop, Outcome::Failure)
            }
        };
        metrics::effects_total(kind, result).increment(1);
        resume
    }

    async fn housekeeping(&self, status: BlockStatus) {
        // Only secrets scheduled by a reconciliation at or before the snapshot
        // boundary are collected, so nothing the state machine could still roll
        // back to is deleted here.
        let result = match self.secrets.prune_scheduled_secrets(status.safe).await {
            Ok(pruned) => {
                if pruned.keygen > 0 || pruned.signing_nonces > 0 {
                    tracing::debug!(
                        block = status.latest,
                        safe = status.safe,
                        keygen = pruned.keygen,
                        signing_nonces = pruned.signing_nonces,
                        "pruned scheduled group secrets"
                    );
                }
                Outcome::Success
            }
            Err(err) => {
                // A later block retries the collection, and a schedule that was
                // not collected stays valid until it is.
                tracing::warn!(
                    block = status.latest,
                    safe = status.safe,
                    %err,
                    "failed to prune scheduled secrets"
                );
                Outcome::Failure
            }
        };
        metrics::housekeeping_total(result).increment(1);
    }
}

/// An internal error used for logging failed effects.
#[derive(Debug)]
struct InternalError(String);

impl Display for InternalError {
    fn fmt(&self, f: &mut Formatter) -> fmt::Result {
        self.0.fmt(f)
    }
}

impl<E> From<E> for InternalError
where
    E: Error,
{
    fn from(value: E) -> Self {
        Self(value.to_string())
    }
}
