/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EpochRouteImport } from './routes/epoch'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SafeTxRouteImport } from './routes/safeTx'
import { Route as IndexRouteImport } from './routes/index'

const EpochRoute = EpochRouteImport.update({
  id: '/epoch',
  path: '/epoch',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SafeTxRoute = SafeTxRouteImport.update({
  id: '/safeTx',
  path: '/safeTx',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/epoch': typeof EpochRoute
  '/safeTx': typeof SafeTxRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/epoch': typeof EpochRoute
  '/safeTx': typeof SafeTxRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/epoch': typeof EpochRoute
  '/safeTx': typeof SafeTxRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/epoch' | '/safeTx' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/epoch' | '/safeTx' | '/settings'
  id: '__root__' | '/' | '/epoch' | '/safeTx' | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  EpochRoute: typeof EpochRoute
  IndexRoute: typeof IndexRoute
  SafeTxRoute: typeof SafeTxRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/epoch': {
      id: '/epoch'
      path: '/epoch'
      fullPath: '/epoch'
      preLoaderRoute: typeof EpochRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safeTx': {
      id: '/safeTx'
      path: '/safeTx'
      fullPath: '/safeTx'
      preLoaderRoute: typeof SafeTxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  EpochRoute: EpochRoute,
  IndexRoute: IndexRoute,
  SafeTxRoute: SafeTxRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
