name: ci

on:
  pull_request:
  push:
    branches:
      - main

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
          cache: "npm"

      - uses: foundry-rs/foundry-toolchain@v1
        with:
          # We fix the foundry version because of a formatting bug introduced
          # in version 1.7.0.
          # See <https://github.com/foundry-rs/foundry/issues/13362>
          version: v1.5.1

      # https://github.com/taiki-e/install-action/releases/tag/v2.82.6
      - uses: taiki-e/install-action@9bcaee1dcae34154180f412e2fa69355a7cda9f6
        with:
          tool: cargo-llvm-cov

      - run: npm ci
      - run: npm run check
      - run: npm run coverage
      - run: scripts/rust_coverage.sh

      - name: Post Coverage Report
        if: github.event_name == 'pull_request'
        uses: ./.github/actions/report-coverage
        with:
          post-as-step-summary: "true"
          upload-artifact: "true"
