name: integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  integration:
    name: integration (${{ matrix.name }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: sentinel
            just-target: test-integration-sentinel
            log-artifact: sentinel-integration-logs

          - name: validator
            just-target: test-integration-validator
            log-artifact: validator-integration-logs

          - name: validator-reorg-nonce
            just-target: test-integration-validator-reorg-nonce
            log-artifact: validator-integration-reorg-nonce-logs

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - uses: foundry-rs/foundry-toolchain@v1
        with:
          # We fix the foundry version because of a formatting bug introduced
          # in version 1.7.0.
          # See <https://github.com/foundry-rs/foundry/issues/13362>
          version: v1.5.1

      - uses: ./.github/actions/install-just

      - run: just ${{ matrix.just-target }}

      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.log-artifact }}
          path: "*_logs.txt"
          if-no-files-found: ignore
