name: rust

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - run: |
          cargo fmt --all -- --check
          cargo clippy --workspace --all-targets --locked -- -D warnings
          cargo test --workspace
